/*
 Navicat Premium Data Transfer

 Source Server         : Digital
 Source Server Type    : MySQL
 Source Server Version : 50718
 Source Host           : localhost:3306
 Source Schema         : helparm.platform

 Target Server Type    : MySQL
 Target Server Version : 50718
 File Encoding         : 65001

 Date: 29/10/2020 23:06:18
*/

SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS = 0;

-- ----------------------------
-- Table structure for nomenclatures
-- ----------------------------

INSERT INTO `nomenclatures`(`name`) VALUES ('Бинты');
INSERT INTO `nomenclatures`(`name`) VALUES ('Шприцы');
INSERT INTO `nomenclatures`(`name`) VALUES ('Вода');
INSERT INTO `nomenclatures`(`name`) VALUES ('Амоксиклав');
INSERT INTO `nomenclatures`(`name`) VALUES ('Бинт марлевый');
INSERT INTO `nomenclatures`(`name`) VALUES ('Гель для рук');
INSERT INTO `nomenclatures`(`name`) VALUES ('Амоксиклав');
INSERT INTO `nomenclatures`(`name`) VALUES ('Бинт марлевый');
INSERT INTO `nomenclatures`(`name`) VALUES ('Гель для рук');
INSERT INTO `nomenclatures`(`name`) VALUES ('палатка');
INSERT INTO `nomenclatures`(`name`) VALUES ('Анальгин');
INSERT INTO `nomenclatures`(`name`) VALUES ('Мониторы Сторм 5900, Диксион Россия');
INSERT INTO `nomenclatures`(`name`) VALUES ('Аспиратор хирургический (вакуумный экстрактор) Dixion-YX930D-1A, SMAF KHP');
INSERT INTO `nomenclatures`(`name`) VALUES ('Пульсоксиметры');
INSERT INTO `nomenclatures`(`name`) VALUES ('Операционный стол');
INSERT INTO `nomenclatures`(`name`) VALUES ('Напольный светильник передвижной');
INSERT INTO `nomenclatures`(`name`) VALUES ('ИВЛ Dixion 530');
INSERT INTO `nomenclatures`(`name`) VALUES ('ИВЛ (наркозный аппарат) РО-9');
INSERT INTO `nomenclatures`(`name`) VALUES ('Наркозный аппарат Dixion 7300');
INSERT INTO `nomenclatures`(`name`) VALUES ('Портативный аппарат ИВЛ BiPAP');
INSERT INTO `nomenclatures`(`name`) VALUES ('Портативный ИВЛ \"Ритм\" модели 100');
INSERT INTO `nomenclatures`(`name`) VALUES ('Наркозный аппарат Drager');
INSERT INTO `nomenclatures`(`name`) VALUES ('Коагулятор');
INSERT INTO `nomenclatures`(`name`) VALUES ('Коагулятор Dixion Altafor 1330 Plus');
INSERT INTO `nomenclatures`(`name`) VALUES ('Инфузоматы');
INSERT INTO `nomenclatures`(`name`) VALUES ('Дефибрилляторы');
INSERT INTO `nomenclatures`(`name`) VALUES ('Кислородный концентратор JAY-5A, Longfian KHP');
INSERT INTO `nomenclatures`(`name`) VALUES ('Кислородные концентраторы Atmung LF-H-10A');
INSERT INTO `nomenclatures`(`name`) VALUES ('ЭОП');
INSERT INTO `nomenclatures`(`name`) VALUES ('Портативный рентген аппарат meX+ 100 - 5кВт: Часть 1 Мониторы плоскопанельный детектор DR Rayence/Samsung 1417 (wifi)');
INSERT INTO `nomenclatures`(`name`) VALUES ('Ларингоскоп');
INSERT INTO `nomenclatures`(`name`) VALUES ('ЭКГ');
INSERT INTO `nomenclatures`(`name`) VALUES ('Отоскоп');
INSERT INTO `nomenclatures`(`name`) VALUES ('Офтальмоскоп');
INSERT INTO `nomenclatures`(`name`) VALUES ('Налобный осветитель');
INSERT INTO `nomenclatures`(`name`) VALUES ('Биполярный пинцет прямой 190мм');
INSERT INTO `nomenclatures`(`name`) VALUES ('Кабель для биполярных пинцетов 3 метра');
INSERT INTO `nomenclatures`(`name`) VALUES ('Рентгензащитные фартуки');
INSERT INTO `nomenclatures`(`name`) VALUES ('Сшивающий аппарат Echelon FLEX + касеты');
INSERT INTO `nomenclatures`(`name`) VALUES ('Воздушные стерилизаторы');
INSERT INTO `nomenclatures`(`name`) VALUES ('Шкаф сухожаровой ГП-40');
INSERT INTO `nomenclatures`(`name`) VALUES ('Анализатор электронейромиографический \"Синапсис\" (станд.) №6000');
INSERT INTO `nomenclatures`(`name`) VALUES ('травматологический набор (1к)');
INSERT INTO `nomenclatures`(`name`) VALUES ('бинт перевязочный (2к)');
INSERT INTO `nomenclatures`(`name`) VALUES ('салфетки антисептические (5к)');
INSERT INTO `nomenclatures`(`name`) VALUES ('раствор рингера для реанимации');
INSERT INTO `nomenclatures`(`name`) VALUES ('салфетки ликозоль (8к)');
INSERT INTO `nomenclatures`(`name`) VALUES ('бинт перевязочный (9к)');
INSERT INTO `nomenclatures`(`name`) VALUES ('бинт перевязочный (10к)');
INSERT INTO `nomenclatures`(`name`) VALUES ('бинт перевязочный (11к)');
INSERT INTO `nomenclatures`(`name`) VALUES ('первичный перевязочный материал (12к)');
INSERT INTO `nomenclatures`(`name`) VALUES ('жгут (13к)');
INSERT INTO `nomenclatures`(`name`) VALUES ('жгут (14к)');
INSERT INTO `nomenclatures`(`name`) VALUES ('жгут(15к)');
INSERT INTO `nomenclatures`(`name`) VALUES ('жгут (16к)');
INSERT INTO `nomenclatures`(`name`) VALUES ('жгут (17шт)');
INSERT INTO `nomenclatures`(`name`) VALUES ('жгут(19к)');
INSERT INTO `nomenclatures`(`name`) VALUES ('жгут(20к)');
INSERT INTO `nomenclatures`(`name`) VALUES ('бинты (21к)');
INSERT INTO `nomenclatures`(`name`) VALUES ('жгут (22к)');
INSERT INTO `nomenclatures`(`name`) VALUES ('анальгин (23к)');
INSERT INTO `nomenclatures`(`name`) VALUES ('Система для инфузионной терапии  (26к)');
INSERT INTO `nomenclatures`(`name`) VALUES ('жгут(27к)');
INSERT INTO `nomenclatures`(`name`) VALUES ('набор хирургическиких инструментов (29к)');
INSERT INTO `nomenclatures`(`name`) VALUES ('Бинты перевязочные (30к)');
INSERT INTO `nomenclatures`(`name`) VALUES ('Стерильные повязки');
INSERT INTO `nomenclatures`(`name`) VALUES ('жгут (31к)');
INSERT INTO `nomenclatures`(`name`) VALUES ('жгут (32к)');
INSERT INTO `nomenclatures`(`name`) VALUES ('урологические катетеры (33к)');
INSERT INTO `nomenclatures`(`name`) VALUES ('перекись 100мл (36к)');
INSERT INTO `nomenclatures`(`name`) VALUES ('перекись100мл (37К)');
INSERT INTO `nomenclatures`(`name`) VALUES ('перекись100мл (37К)');
INSERT INTO `nomenclatures`(`name`) VALUES ('перекись 100мл (38К)');
INSERT INTO `nomenclatures`(`name`) VALUES ('перчатки (39К)');
INSERT INTO `nomenclatures`(`name`) VALUES ('перекись 100мл (40к)');
INSERT INTO `nomenclatures`(`name`) VALUES ('перекись 100мл (41к)');
INSERT INTO `nomenclatures`(`name`) VALUES ('перчатки (42к)');
INSERT INTO `nomenclatures`(`name`) VALUES ('простыня хирургическая стерильная (44к)');
INSERT INTO `nomenclatures`(`name`) VALUES ('перекись 100мл');
INSERT INTO `nomenclatures`(`name`) VALUES ('перекись100мл (46к)');
INSERT INTO `nomenclatures`(`name`) VALUES ('взрослые подгузники размер 3 (100х150) 30шт/уп (48к)');
INSERT INTO `nomenclatures`(`name`) VALUES ('перчатки стерильные (51к)');
INSERT INTO `nomenclatures`(`name`) VALUES ('гемостатик (53к)');
INSERT INTO `nomenclatures`(`name`) VALUES ('натрий хлор 0,9 500мл');
INSERT INTO `nomenclatures`(`name`) VALUES ('натрий хлор 0,9 500мл (57к)');
INSERT INTO `nomenclatures`(`name`) VALUES ('\"Натрий хлор 0,9 200мл - 12шт Натрий хлор 0,9 500мл - 2шт\" (59к)');
INSERT INTO `nomenclatures`(`name`) VALUES ('натрий хлор 0,9 500мл (62к)');
INSERT INTO `nomenclatures`(`name`) VALUES ('натрий хлор 0,9 400мл (63к)');
INSERT INTO `nomenclatures`(`name`) VALUES ('интралипид 20% 100мл  - парантеральное питание');
INSERT INTO `nomenclatures`(`name`) VALUES ('натрий хлор 0,9% 500мл');
INSERT INTO `nomenclatures`(`name`) VALUES ('вата (66к)');
INSERT INTO `nomenclatures`(`name`) VALUES ('\"Метипред 30 таблеток/ уп 4мг - 10шт Дексаметазон 0,5мг - 3шт Кортеф 100 тб / уп, 10мг - 3шт\" (68к)');
INSERT INTO `nomenclatures`(`name`) VALUES ('зеленка 10мл (69к)');
INSERT INTO `nomenclatures`(`name`) VALUES ('фильтр для ИВЛ (70к)');
INSERT INTO `nomenclatures`(`name`) VALUES ('йод 25мл (71к)');
INSERT INTO `nomenclatures`(`name`) VALUES ('перекись 100мл');
INSERT INTO `nomenclatures`(`name`) VALUES ('простыня хирургическая стерильная (73к)');
INSERT INTO `nomenclatures`(`name`) VALUES ('простыня хирургическая стерильная (75к)');
INSERT INTO `nomenclatures`(`name`) VALUES ('простыня хирургическая стерильная (76к)');
INSERT INTO `nomenclatures`(`name`) VALUES ('простыня хирургическая стерильная (78к)');
INSERT INTO `nomenclatures`(`name`) VALUES ('простыня хирургическая стерильная (77к)');
INSERT INTO `nomenclatures`(`name`) VALUES ('простыня хирургическая стерильная (79к)');
INSERT INTO `nomenclatures`(`name`) VALUES ('халат хирургический стерильный (81к)');
INSERT INTO `nomenclatures`(`name`) VALUES ('халат хирургический стерильный (82к)');
INSERT INTO `nomenclatures`(`name`) VALUES ('халат хирургический стерильный (83к)');
INSERT INTO `nomenclatures`(`name`) VALUES ('халат хирургический стерильный (84к)');
INSERT INTO `nomenclatures`(`name`) VALUES ('халат нестерильный (85к)');
INSERT INTO `nomenclatures`(`name`) VALUES ('халат хирургический стерильный (86к)');
INSERT INTO `nomenclatures`(`name`) VALUES ('халат нестерильный (87к)');
INSERT INTO `nomenclatures`(`name`) VALUES ('\"бетадин раствор 10 процентный\" (88к)');
INSERT INTO `nomenclatures`(`name`) VALUES ('перчатки стерильные (90к)');
INSERT INTO `nomenclatures`(`name`) VALUES ('глюкоза (91к)');
INSERT INTO `nomenclatures`(`name`) VALUES ('халат хирургический стерильный (94к)');
INSERT INTO `nomenclatures`(`name`) VALUES ('шины для ног(96к)');
INSERT INTO `nomenclatures`(`name`) VALUES ('Интубационные трубки (95к)');
INSERT INTO `nomenclatures`(`name`) VALUES ('Халат хирургический(201к)');
INSERT INTO `nomenclatures`(`name`) VALUES ('ципрофлоксацин 200мг/ 100мл (97к)');
INSERT INTO `nomenclatures`(`name`) VALUES ('раствор рингера для реанимации 200мл (98к)');
INSERT INTO `nomenclatures`(`name`) VALUES ('Димедрол 20 таб/уп (99к)');
INSERT INTO `nomenclatures`(`name`) VALUES ('перекись 22 pc 40 ml, 5 pc 100ml (100к)');
INSERT INTO `nomenclatures`(`name`) VALUES ('Хирургические костюмы(206к)');
INSERT INTO `nomenclatures`(`name`) VALUES ('перекись 100мл (101)');
INSERT INTO `nomenclatures`(`name`) VALUES ('Хирургические костюмы(207к)');
INSERT INTO `nomenclatures`(`name`) VALUES ('Хирургические простыни(210к)');
INSERT INTO `nomenclatures`(`name`) VALUES ('перчатки латексные размер 7 (102к)');
INSERT INTO `nomenclatures`(`name`) VALUES ('Хирургические простыни(211к)');
INSERT INTO `nomenclatures`(`name`) VALUES ('перекись 100мл (103к)');
INSERT INTO `nomenclatures`(`name`) VALUES ('перекись 100мл (104к)');
INSERT INTO `nomenclatures`(`name`) VALUES ('Антибиотики(218к)');
INSERT INTO `nomenclatures`(`name`) VALUES ('жгуты(219к)');
INSERT INTO `nomenclatures`(`name`) VALUES ('\"Фильтр для трахестомии - 90шт Зонд для перорального питания - 10шт Канюли для трахеостомии - 20шт Центральный венозный катетер - 10шт\" (105к)');
INSERT INTO `nomenclatures`(`name`) VALUES ('жгуты(220к)');
INSERT INTO `nomenclatures`(`name`) VALUES ('фильтр для ИВЛ (106к)');
INSERT INTO `nomenclatures`(`name`) VALUES ('жгуты(221к)');
INSERT INTO `nomenclatures`(`name`) VALUES ('зонд желудочный (107к)');
INSERT INTO `nomenclatures`(`name`) VALUES ('жгуты(222к)');
INSERT INTO `nomenclatures`(`name`) VALUES ('\"Альбумин 20 % (109к)');
INSERT INTO `nomenclatures`(`name`) VALUES ('Центральный венозный катетер (95к)');
INSERT INTO `nomenclatures`(`name`) VALUES ('жгуты(223к)');
INSERT INTO `nomenclatures`(`name`) VALUES ('шины иммобилизационные  (109к)');
INSERT INTO `nomenclatures`(`name`) VALUES ('жгуты(224к)');
INSERT INTO `nomenclatures`(`name`) VALUES ('бетадин раствор 10%');
INSERT INTO `nomenclatures`(`name`) VALUES ('Хирургические простыни(208к)');
INSERT INTO `nomenclatures`(`name`) VALUES ('Амбу мешок');
INSERT INTO `nomenclatures`(`name`) VALUES ('Хирургические простыни(209к)');
INSERT INTO `nomenclatures`(`name`) VALUES ('Кислородные маски');
INSERT INTO `nomenclatures`(`name`) VALUES ('шприцы (112к)');
INSERT INTO `nomenclatures`(`name`) VALUES ('Пантено+гепар мазь(225к)');
INSERT INTO `nomenclatures`(`name`) VALUES ('жгуты(226к)');
INSERT INTO `nomenclatures`(`name`) VALUES ('жгуты(227к)');
INSERT INTO `nomenclatures`(`name`) VALUES ('жгуты(228к)');
INSERT INTO `nomenclatures`(`name`) VALUES ('жгуты(229к)');
INSERT INTO `nomenclatures`(`name`) VALUES ('жгуты(230к)');
INSERT INTO `nomenclatures`(`name`) VALUES ('жгуты(231к)');
INSERT INTO `nomenclatures`(`name`) VALUES ('Аминовен 10 % 500мл (117к)');
INSERT INTO `nomenclatures`(`name`) VALUES ('жгуты(232к)');
INSERT INTO `nomenclatures`(`name`) VALUES ('жгуты(233к)');
INSERT INTO `nomenclatures`(`name`) VALUES ('жгуты(234к)');
INSERT INTO `nomenclatures`(`name`) VALUES ('жгуты(235к)');
INSERT INTO `nomenclatures`(`name`) VALUES ('аминовен 10 % 500мл (119к)');
INSERT INTO `nomenclatures`(`name`) VALUES ('жгуты(236к)');
INSERT INTO `nomenclatures`(`name`) VALUES ('аминовен 10 % 500мл (120к)');
INSERT INTO `nomenclatures`(`name`) VALUES ('аминовен 10 % 500мл (121к)');
INSERT INTO `nomenclatures`(`name`) VALUES ('Хирургические простыни стерильные(237к)');
INSERT INTO `nomenclatures`(`name`) VALUES ('Периферический венозный катетер(95к)');
INSERT INTO `nomenclatures`(`name`) VALUES ('Бинты стерильные(238к)');
INSERT INTO `nomenclatures`(`name`) VALUES ('препараты для реанимации препаратов анастетитки (122к)');
INSERT INTO `nomenclatures`(`name`) VALUES ('Гемостатическая губка(301К)');
INSERT INTO `nomenclatures`(`name`) VALUES ('атропин 1мл 10ампул/уп (123к)');
INSERT INTO `nomenclatures`(`name`) VALUES ('Стерильные салфетки(239к)');
INSERT INTO `nomenclatures`(`name`) VALUES ('антибиотики (124к)');
INSERT INTO `nomenclatures`(`name`) VALUES ('Шприцы 20 мл(302к)');
INSERT INTO `nomenclatures`(`name`) VALUES ('Стерильные перчатки(240к)');
INSERT INTO `nomenclatures`(`name`) VALUES ('Памперсы  Пеленки');
INSERT INTO `nomenclatures`(`name`) VALUES ('Гемостатическая губка(303к)');
INSERT INTO `nomenclatures`(`name`) VALUES ('памперсы 127к');
INSERT INTO `nomenclatures`(`name`) VALUES ('Бинты фиксирующие(242к)');
INSERT INTO `nomenclatures`(`name`) VALUES ('\"Набор для ранимации (интубационные трубки мочевые катетеры -35 Жгут -100 капельницы фильтры шовный материал противоожоговые наклейки бинты)\" (131к)');
INSERT INTO `nomenclatures`(`name`) VALUES ('Шприцы(243к)');
INSERT INTO `nomenclatures`(`name`) VALUES ('салфетки антисептические (132к)');
INSERT INTO `nomenclatures`(`name`) VALUES ('салфетки антисептические (133к)');
INSERT INTO `nomenclatures`(`name`) VALUES ('Антибиотики(244к)');
INSERT INTO `nomenclatures`(`name`) VALUES ('салфетки антисептические (134к)');
INSERT INTO `nomenclatures`(`name`) VALUES ('салфетки антисептические (135к)');
INSERT INTO `nomenclatures`(`name`) VALUES ('салфетки антисептические (136к)');
INSERT INTO `nomenclatures`(`name`) VALUES ('Бинты стерильные(245к)');
INSERT INTO `nomenclatures`(`name`) VALUES ('физраствор 500мл (137к)');
INSERT INTO `nomenclatures`(`name`) VALUES ('Асептолин(246к)');
INSERT INTO `nomenclatures`(`name`) VALUES ('Бинты стерильные(306к)');
INSERT INTO `nomenclatures`(`name`) VALUES ('Бинты стерильные(247к)');
INSERT INTO `nomenclatures`(`name`) VALUES ('бахилы (140к)');
INSERT INTO `nomenclatures`(`name`) VALUES ('бахилы (141к)');
INSERT INTO `nomenclatures`(`name`) VALUES ('бахилы (142к)');
INSERT INTO `nomenclatures`(`name`) VALUES ('Вата стерильная(248к)');
INSERT INTO `nomenclatures`(`name`) VALUES ('халат нестерильный (143к)');
INSERT INTO `nomenclatures`(`name`) VALUES ('халат нестерильный (144к)');
INSERT INTO `nomenclatures`(`name`) VALUES ('Хлорид Натрия 0,9%(250к)');
INSERT INTO `nomenclatures`(`name`) VALUES ('Трансп.шины(312к)');
INSERT INTO `nomenclatures`(`name`) VALUES ('памперсы (145ш)');
INSERT INTO `nomenclatures`(`name`) VALUES ('Бинты стерильные(253к)');
INSERT INTO `nomenclatures`(`name`) VALUES ('Марля(312к)');
INSERT INTO `nomenclatures`(`name`) VALUES ('памперсы (146к)');
INSERT INTO `nomenclatures`(`name`) VALUES ('Катетеры бабочки для систем(313к)');
INSERT INTO `nomenclatures`(`name`) VALUES ('памперсы (147к)');
INSERT INTO `nomenclatures`(`name`) VALUES ('Диклофенак/дротаверин(но- шпа)(50шт/47шт)(254к)');
INSERT INTO `nomenclatures`(`name`) VALUES ('памперсы (148к)');
INSERT INTO `nomenclatures`(`name`) VALUES ('Жгуты(317к)');
INSERT INTO `nomenclatures`(`name`) VALUES ('подгузники для взрослых (149к)');
INSERT INTO `nomenclatures`(`name`) VALUES ('Бинт липкий(255к)');
INSERT INTO `nomenclatures`(`name`) VALUES ('\"Анальгин 2мл - 72шт Димедрол 1мл - 6шт Диклофенак 3мл\"');
INSERT INTO `nomenclatures`(`name`) VALUES ('Жгуты(318к)');
INSERT INTO `nomenclatures`(`name`) VALUES ('Спазмолитики(256к)');
INSERT INTO `nomenclatures`(`name`) VALUES ('Йод/зеленка(65шт/25шт)(257к)');
INSERT INTO `nomenclatures`(`name`) VALUES ('Биполярный пинцет прямой 190мм(328/1)');
INSERT INTO `nomenclatures`(`name`) VALUES ('Хлоргексидин 100мл(258к)');
INSERT INTO `nomenclatures`(`name`) VALUES ('Кабель для биполярных пинцетов 3 метра(328/2)');
INSERT INTO `nomenclatures`(`name`) VALUES ('Кабель для биполярных пинцетов 3 метра(329/1)');
INSERT INTO `nomenclatures`(`name`) VALUES ('Биполярный пинцет прямой 190мм(329/2 к)');
INSERT INTO `nomenclatures`(`name`) VALUES ('Дефибриллятор(330к)');
INSERT INTO `nomenclatures`(`name`) VALUES ('Дефибриллятор(331к)');
INSERT INTO `nomenclatures`(`name`) VALUES ('средство для дезинфекции (152к)');
INSERT INTO `nomenclatures`(`name`) VALUES ('Эндотрахеальные трубки(332к)');
INSERT INTO `nomenclatures`(`name`) VALUES ('перчатки');
INSERT INTO `nomenclatures`(`name`) VALUES ('Марля 90 см(259к)');
INSERT INTO `nomenclatures`(`name`) VALUES ('Катетеры центральные венозные (332к)');
INSERT INTO `nomenclatures`(`name`) VALUES ('Инфузионные катетеры');
INSERT INTO `nomenclatures`(`name`) VALUES ('бинты 7/14(259к)');
INSERT INTO `nomenclatures`(`name`) VALUES ('Дренажные трубки(333к)');
INSERT INTO `nomenclatures`(`name`) VALUES ('бинты 5/10(259к)');
INSERT INTO `nomenclatures`(`name`) VALUES ('Лейкопластыри без лек.аппликац. 10х35(336к)');
INSERT INTO `nomenclatures`(`name`) VALUES ('эластичные бинты(259к)');
INSERT INTO `nomenclatures`(`name`) VALUES ('Инфузионные катетеры (156к)');
INSERT INTO `nomenclatures`(`name`) VALUES ('фиксирующий бинт+резиновый(259к)');
INSERT INTO `nomenclatures`(`name`) VALUES ('Инфузионные катетеры (157к)');
INSERT INTO `nomenclatures`(`name`) VALUES ('Простыни хирургические(345к)');
INSERT INTO `nomenclatures`(`name`) VALUES ('Простыни хирургические(346к)');
INSERT INTO `nomenclatures`(`name`) VALUES ('Проводник инфузионный(260к)');
INSERT INTO `nomenclatures`(`name`) VALUES ('Простыни хирургические(347к)');
INSERT INTO `nomenclatures`(`name`) VALUES ('Ципрофлоксоцин(261к)');
